backend:
  name: git-gateway
  branch: master

media_folder: static/media
public_folder: /media

collections:
  - name: "member"
    label: "Medlemsformulär"
    files:
      - file: "src/pages/member/index.md"
        label: "Medlemsformulär"
        name: "member"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "member"}
          - {label: "Länk", name: "url", widget: "string"}
  
  - name: "event"
    label: "Event"
    folder: "src/pages/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "event"}
      - {label: "Rubrik", name: "title", widget: "string"}
      - {label: "Tid", name: "date", widget: "date"}
      - {label: "Publicerat", name: "date", widget: "datetime"}
      - {label: "Text", name: "body", widget: "markdown"}

  - name: "nyheter"
    label: "Nyheter"
    folder: "src/pages/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "news"}
      - {label: "Rubrik", name: "title", widget: "string"}
      - {label: "Publicerat", name: "date", widget: "datetime"}
      - {label: "Text", name: "body", widget: "markdown"}

  - name: "sidor"
    label: "Sidor"
    files:
      - file: "src/pages/about/index.md"
        label: "Om Ölbruket"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Rubrik", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/board/index.md"
        label: "Styrelse"
        name: "board"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "board-page"}
          - {label: "Rubrik", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Styrelsemedlemmar"
            name: "boardMembers"
            widget: list
            fields:
              - {label: "Namn", name: "name", widget: "string"}
              - {label: "Post", name: "post", widget: "string"}
              - {label: "Bild", name:"image", widget: "image"}
              - {label: "Email", name: "email", widget: "string"}
      - file: "src/pages/documents/index.md"
        label: "Dokument"
        name: "documents"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "documents-page"}  
          - {label: "Rubrik", name: "title", widget: "string"}
          - {label: "Intro", name: "intro", widget: "markdown"}
          - {label: "Kategorier", name: categories, widget: list, fields: [
            {label: "Kategori", name: category, widget: object, fields: [
              {label: "Namn", name: "categoryName", widget: "string"},
              {label: "Filer", name: "files", widget: "list", fields : [
                {label: "Namn", name: "name", widget: "string"}, 
                {label: "Fil", name: "file", widget: "file"}]}
              ]}
            ]}
