backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "event"
    label: "Event"
    folder: "src/pages/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "event"}
      - {label: "Titel", name: "titel", widget: "string"}
      - {label: "Tid", name: "date", widget: "datetime"}
      - {label: "Publicerat", name: "date", widget: "datetime"}
      - {label: "Text", name: "body", widget: "markdown"}

  - name: "nyheter"
    label: "Nyheter"
    folder: "src/pages/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "event"}
      - {label: "Titel", name: "titel", widget: "string"}
      - {label: "Publicerat", name: "date", widget: "datetime"}
      - {label: "Text", name: "body", widget: "markdown"}

  - name: "sidor"
    label: "Sidor"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/board/index.md"
        label: "Styrelse"
        name: "styrelse"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "board-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/docuemnts/index.md"
        label: "Dokument"
        name: "dokument"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "documents-page"}  
          - {label: "Filer", name: filer, widget: list, fields: [{label: Titel, name: titel, widget: string}, {label: Fil, name: fil, widget: file}]}